language: haskell
ghc: 7.8

before_install:
  - cabal install hpc-coveralls

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test

after_script:
  - hpc-coveralls spec --exclude-dir=test --display-report
